name: flutter_all_in_one_admob_view
description: Easy to use Admob to earn money your app all in one admob view and not much time to config.
version: 1.0.1
homepage: https://github.com/kdrtech/flutter_admob_view
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  google_mobile_ads: ^5.0.0
  flutter:
    sdk: flutter
dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
